---
- name: Install SBCL
  apt: name=sbcl state=present update_cache=yes

- name: Install time
  apt: name=time state=present update_cache=yes

- name: Checkout SBCL
  git: repo=git://git.code.sf.net/p/sbcl/sbcl dest=/sbcl accept_hostkey=yes
  
- name: Make SBCL
  command: sh make.sh chdir=/sbcl

- name: Remove apt-gets SBCL
  apt: name=sbcl state=absent
  
- name: Install SBCL
  command: sh install.sh chdir=/sbcl


