---
- hosts: dev
  sudo: yes
  vars: 
    proxy_url: "http://{{ proxy_user }}:{{ proxy_password }}@{{ proxy_host }}:{{ proxy_port }}"
    env: 
      http_proxy: "{{ proxy_url }}"
      https_proxy: "{{ proxy_url }}"
  roles:
    - common
    - ruby
    - shen
    - maven
    - smlnj
    - rebar
    - java
    - erlang
    

