---
- hosts: dev
  sudo: yes
  vars: 
    proxy_url: "http://{{ proxy_user }}:{{ proxy_password }}@{{ proxy_host }}:{{ proxy_port }}"
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"
    env: 
      http_proxy: "{{ proxy_url }}"
      https_proxy: "{{ proxy_url }}"
  roles:
    - common
    - ruby
    - shen
    - maven
    - smlnj
    #- rebar
    - java
    - erlang
    

