---
- hosts: dev
  sudo: yes
  vars: 
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"
  roles:
    - common
    - ruby
    - shen
    - maven
    - smlnj
    - java
    - rebar
    - erlang
    - node
    - jekyll
    - nginx
    - gulp
    - leiningen
    - riak    
    

