---
- name: Adding SMLNJ repo
  lineinfile: dest=/etc/apt/sources.list line="{{ item }}"
  with_items:
    - deb http://cz.archive.ubuntu.com/ubuntu trusty main universe


- name: Install SML
  apt: name=smlnj state=present



